basic/api/urls.py
from django.conf.urls import url
from django.contrib import admin

from .views import (
    TemplatesListView,
    TemplatesUploadView,
    SubscribedEmailListView,
    SubscribedEmailCreateView,
    # SendTemplate

)

urlpatterns = [
    url(r'^subscribed_email_list/$', SubscribedEmailListView.as_view(), name='subscribed_email_list'),
    url(r'^subscribed_email/create/$', SubscribedEmailCreateView.as_view(), name='subscribed_email_create'),
    url(r'^templates_list/$', TemplatesListView.as_view(), name='templates_list'),
    url(r'^templates_list/upload/$', TemplatesUploadView.as_view(), name='templates_list_upload'),
    # url(r'^templates_list/parse/(?P<pk>\d+)', TemplatesParseView.as_view(), name='templates_parse')
    # url(r'^send_template/(?P<pk>.+)$', SendTemplate.as_view(), name='send_template')

]

basic/urls.py
from django.conf.urls import url, include
from basic import views

urlpatterns = [
    url(r'^$', views.home, name='home'),
    url(r'^upload_templates/$', views.uploadTemplates, name='upload_templates'),
    url(r'^send_template/(?P<pk>.+)$', views.send_template, name='send_template')
]

sendmail/urls.py
from django.conf.urls import url
from django.conf.urls import include
from django.contrib import admin
from django.conf import settings
from django.views.static import serve
from django.conf.urls.static import static
from basic import views as basic_views
from django.contrib.auth import views as auth_views

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^login/$', auth_views.login, {'template_name': 'account/login.html'}, name='login'),
    url(r'^logout/$', auth_views.logout, {'next_page': '/'}, name='logout'),
    url(r'', include('basic.urls', namespace='basic')),
    url(r'^api/basic/', include('basic.api.urls', namespace='api-basic')),
    url(r'^api/account/', include('account.api.urls', namespace='account-basic'))

]

handler400 = basic_views.error400  # noqa
handler403 = basic_views.error403  # noqa
handler404 = basic_views.error404  # noqa
handler500 = basic_views.error500  # noqa
handler200 = basic_views.error200  # noqa

# when debug is True

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

basic/models.py
from django.contrib.auth.models import User
from django.db import models
from basic.validators import validate_file_extension
# Create your models here.

# Model Class for Email which subscribed to my site
class SubscribedEmail(models.Model):
    email_address = models.EmailField(unique=True)

    def __str__(self):
        return str(self.email_address)


# Model Class for Saving Uploaded Email
class EmailTemplates(models.Model):
    templates_owner = models.ForeignKey(User, on_delete=models.CASCADE)
    templates = models.FileField(validators=[validate_file_extension])
    number_of_times_templates_send = models.IntegerField(default=0, null=True, blank=True)

    def __str__(self):
        return str(self.templates)


# Model Class for Saving Uploaded Image
class SaveImageFromTemplates(models.Model):
    parentTemplates = models.ForeignKey(EmailTemplates, on_delete=models.CASCADE, default=None)
    imageSource = models.CharField(max_length=10000)

    def __str__(self):
        return str(self.imageSource)


# Model for Email Send
class SendEmail(models.Model):
    template = models.ForeignKey(EmailTemplates, on_delete=models.DO_NOTHING)
    mail_send_user = models.ForeignKey(User, on_delete=models.DO_NOTHING)
    number_of_mail = models.IntegerField(default=0)

    def __str__(self):
        return str(self.template)

basic/forms.py
from django import forms
from basic.models import SubscribedEmail, EmailTemplates


class EmailSubscriberAddForm(forms.ModelForm):
    email_address = forms.EmailField(widget=forms.TextInput(attrs={'placeholder': 'spam.free@yourmail.com'}))

    class Meta:
        model = SubscribedEmail
        fields = ['email_address']

    def clean_email_address(self):
        if SubscribedEmail.objects.filter(email_address=self.cleaned_data.get('email_address', None)).count() > 0:
            raise forms.ValidationError("User with this email already exists.")

        return self.cleaned_data.get('email_address')


class EmailTemplatesUploadForm(forms.ModelForm):
    templates = forms.FileField()

    class Meta:
        model = EmailTemplates
        fields = ['templates']

basic/api/views.py
from rest_framework import mixins, viewsets
from rest_framework.generics import (
    ListAPIView,
    CreateAPIView
)
# Use for Permission
from rest_framework.permissions import (
    AllowAny, IsAuthenticated
)

from .serializers import TemplatesSerializer, EmailSerializer

from basic.models import EmailTemplates, SubscribedEmail

from basic.views import parse_template

from rest_framework.status import (
    HTTP_400_BAD_REQUEST,
    HTTP_404_NOT_FOUND,
    HTTP_200_OK
)


class TemplatesListView(ListAPIView):
    print("TemplatesListView")
    serializer_class = TemplatesSerializer
    queryset = EmailTemplates.objects.all()
    permission_classes = [IsAuthenticated]


class TemplatesUploadView(CreateAPIView):
    print("TemplatesUploadView")
    serializer_class = TemplatesSerializer
    permission_classes = [IsAuthenticated]

    # After uploading the templates via DRF, run the parse_template function
    def perform_create(self, serializer):
        instance = serializer.save()
        print("Instance id in DRF", instance.pk)
        parse_template(instance.pk)
        req = self.request
        print("Request", req)


class SubscribedEmailListView(ListAPIView):
    serializer_class = EmailSerializer
    queryset = SubscribedEmail.objects.all()
    permission_classes = [IsAuthenticated]


class SubscribedEmailCreateView(CreateAPIView):
    serializer_class = EmailSerializer
    permission_classes = [IsAuthenticated]

# class SendTemplate()

basic/views.py
import time
from basic.helper import open_file, write_in_file, get_addr
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.shortcuts import render, redirect, get_object_or_404
import os
import re
from django.core.mail import EmailMultiAlternatives
from django.template.loader import get_template
from basic.forms import EmailSubscriberAddForm, EmailTemplatesUploadForm
from basic.models import EmailTemplates, SubscribedEmail, SaveImageFromTemplates, SendEmail
from django.contrib import messages
from slimit import ast
from slimit.parser import Parser
from slimit.visitors import nodevisitor
from bs4 import BeautifulSoup
from django.conf import settings
from urllib.request import urlopen as uReq
from selenium import webdriver

i = 0
args = []

pattern = re.compile(r"(.*).setOption\((.*)\);")  # Search for the .setoption() function --> echart.js
# Search for the new Chart() function --> chart.js
pattern1 = re.compile(r"var (.*) = new Chart\((.*),(.*)\)", re.MULTILINE | re.DOTALL)
# Search for the location where script file is making charts in echart.js
pattern2 = re.compile(
    r"echarts.init\(document.getElementById\((.*)\)\)|echarts.init\(document.getElementsByClassName\((.*)\)\)"
)


# Create your views here.
# For Home Page
def home(request):
    # Fetch templates from the Email_templates database
    emailTemplates = EmailTemplates.objects.all()
    # For Subscribe mail functionality
    if request.method == "POST":
        add_form = EmailSubscriberAddForm(request.POST or None)
        if add_form.is_valid():
            # print("Form is valid")
            instance = add_form.save(commit=False)
            # print("b")
            instance.save()
            # print("a")
            # messages.success(request, 'You have been subscribed')
            return redirect('basic:home')
        else:
            add_form = EmailSubscriberAddForm(request.POST or None)
    else:
        add_form = EmailSubscriberAddForm()

    context = {
        'add_form': add_form,
        'email_templates': emailTemplates,
        'errors': add_form.errors,
    }
    # print("Request User", request.user)
    return render(request, 'basic/index.html', context)


# Function for uploading the templates
@login_required
def uploadTemplates(request):
    # For uploading templates
    if request.method == "POST":
        add_form = EmailTemplatesUploadForm(request.POST, request.FILES)
        # print(os.access(str(request.FILES['templates']), os.W_OK))
        if add_form.is_valid():
            print("Form is valid")
            instance = add_form.save(commit=False)
            # print("a", type(instance))
            instance.templates_owner = request.user
            # print("b", instance)
            instance.save()
            # print(instance.pk)
            # Commented for testing purpose
            parse_template(instance.pk)
            #  To fetch charts and convert them into images
            return redirect('basic:home')
        else:
            print("Form is not valid")
            add_form = EmailTemplatesUploadForm(request.POST, request.FILES)
    else:
        print("asd")
        add_form = EmailTemplatesUploadForm()
    context = {'upload_form': add_form}
    return render(request, 'basic/upload_templates.html', context)


# Function for parsing templates and downloading the image from it
def parse_template(pk):
    checkparse = SaveImageFromTemplates.objects.all().filter(parentTemplates_id=pk)
    if checkparse:
        print("Already")
    else:
        # To check for different chart scripts and appending the image conversion script
        print("create")
        append_template(pk)
        emailTemplates = get_object_or_404(EmailTemplates, id=pk)
        template_name = emailTemplates
        # Open browser and get data
        browser = webdriver.Firefox()
        site = 'http://127.0.0.1:8000/media/' + str(template_name)
        browser.get(site)
        time.sleep(10)
        soup = BeautifulSoup(browser.page_source, "html.parser")
        # To parse for all image tags and fetch their image sources
        id_pattern = re.compile(r"url[0-9]{1,6}")
        img_tags = soup.find_all(id=id_pattern)
        # print("img", img_tags)
        urls = [img['src'] for img in img_tags]

        ik = 0

        Directory = settings.MEDIA_ROOT
        os.chdir(Directory)
        for contains in urls:
            # Storing the fetched image in the media folder
            # print("Reached inside loop")
            imageName = str(template_name) + "_" + str(ik)

            ImageFile = open(imageName + '.jpeg', 'wb')
            ImageFile.write(uReq(contains).read())
            ImageFile.close()
            # Creating an instance of the stored image and saving it
            instance = SaveImageFromTemplates()
            instance.parentTemplates = emailTemplates
            instance.imageSource = 'http://127.0.0.1:8000/media/' + str(imageName) + str('.jpeg')
            instance.save()
            ik = ik + 1
        browser.quit()
        # For removing all the script and unwanted tags
        parse_and_append_templates(pk)
        # Send Templates
        # send_template(pk)

    # To append the script to add img tag and and to convert chart to image


def append_template(pk):
    print("append")
    # open the file which is uploaded now
    # Calls helper function to open the concerned file
    testFile = open_file(pk)
    # Using BeautifoulSoup for parsing
    soup = BeautifulSoup(testFile, "html.parser")
    # find all script file
    for script in soup.find_all('script'):
        script.text.replace('\n', '')
        # initiates slimit parser tree
        parser = Parser()
        # to parse through the script in html
        tree = parser.parse(script.text)

        for node in nodevisitor.visit(tree):
            # Calls function which appends image conversion code based on type of charts

            append_to_chart(node, soup, script)
            # Calls helper function to write the changed soup
            write_in_file(pk, soup)


# append the image at right place
def parse_and_append_templates(pk):
    global i
    # Calls helper function to open the concerned file
    testFile = open_file(pk)
    soup = BeautifulSoup(testFile, "html.parser")
    # Removing all the script tags
    [x.extract() for x in soup.find_all('script')]
    id_pattern = re.compile(r"url[0-9]{1,6}")
    # Removing all the image tags
    # [y.extract() for y in soup.find_all(id=id_pattern)]
    # Calls helper function to write the changed soup
    write_in_file(pk, soup)
    instance_image = SaveImageFromTemplates.objects.filter(parentTemplates_id=pk)
    k = 0

    imgs = soup.find_all('img', {'id': id_pattern})
    all_canvas = soup.find_all('canvas')
    if imgs and not all_canvas:
        for img_src, item in zip(instance_image, imgs):
            new_tag = soup.new_tag('img',
                                   src=img_src,
                                   id='url' + str(k))
            Div = item.previous_sibling.previous_sibling
            Div.append(new_tag)
            item.extract()
            write_in_file(pk, soup)
            k = k + 1

    else:
        [y.extract() for y in soup.find_all(id=id_pattern)]
        # Removing all the canvas in the Chart.js containing html
        for canvas, img_src in zip(all_canvas, instance_image):
            new_tag = soup.new_tag('img',
                                   src=img_src,
                                   id='url' + str(k),
                                   style="padding:15px; "
                                         "margin: 15px; "
                                         "align-self: center; "
                                         "display: inline-flex !important;")
            canvas.replaceWith(new_tag)
            write_in_file(pk, soup)
            k = k + 1

    i = 0


# For Sending mail as templates
def send_template(request, pk):
    subscribedEmail = SubscribedEmail.objects.values_list('email_address', flat=True)
    print(subscribedEmail)
    to = []
    to.append(subscribedEmail[0])
    for se in subscribedEmail:
        if se not in to:
            to.append(se)
    plaintext = get_template('basic/email.txt')
    # Calls helper function to get the address of the concerned file
    template_addr = get_addr(pk)
    htmly = get_template(template_addr)
    html_content = htmly.render()
    subject, from_email = 'Hello from vPhrase', 'evicharya@gmail.com'
    text_content = plaintext.render()
    msg = EmailMultiAlternatives(subject, text_content, from_email, to)
    msg.attach_alternative(html_content, "text/html")
    try:
        msg.send()
        templates = EmailTemplates.objects.filter(id=pk)
        num = templates.values_list('number_of_times_templates_send', flat=True)
        templates_owner = templates.values_list('templates_owner_id', flat=True)
        print("Num", num)
        user = User.objects.get(id=templates_owner[0])
        templates.update(number_of_times_templates_send=(int(num[0]) + 1))
        emailTemplates = get_object_or_404(EmailTemplates, id=pk)
        SendEmail.objects.create(template=emailTemplates, mail_send_user=user, number_of_mail=int(num[0]))
    except:
        print("Sorry there was some Problem")
    return render(request, 'basic/index.html')
    # return render(request, 'basic/email_sending_complete.html')


def append_to_chart(node, soup, script):
    global i
    # If the tree node is a Functional Call the html is compared with the regex
    if isinstance(node, ast.FunctionCall) and re.findall(pattern2, node.to_ecma()):
        for j in range(len(re.findall(pattern2, node.to_ecma()))):
            # Declared global as is to be used in parse_and_append function
            global args
            # For storing the ids of the tags in which charts are rendered
            arg3 = re.search(pattern2, node.to_ecma()).group(1)

basic/templates/basic/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>vPhrase SendMail</title>

    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    {% block style %}
    {% endblock style %}
</head>
<body>
<div class="jumbotron text-center">
    <h1>Send Mail</h1>
    {% if user.is_authenticated %}
        <P>
            <a href="{% url 'logout' %}" id="logout_link">
                <button type="submit" class="btn btn-default" style="background-color: #00bda0; color: #fff">
                    Log Out
                </button>
            </a>
        </P>
    {% else %}
        <P>
            <a href="{% url 'login' %}" id="login_link">
                <button type="submit" class="btn btn-default" style="background-color: #00bda0; color: #fff">
                    Log In
                </button>
            </a>
        </P>
    {% endif %}
</div>
{% block content %}
{% endblock %}
</body>
</html>

basic/templates/basic/email_creator.html
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta http-equiv="Content-Type" content="text/html; charset=utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1, minimum-scale=1, maximum-scale=1">
<title></title>
<style type="text/css">
    @import url(https://fonts.googleapis.com/css?family=Open+Sans:400,600);
    @import url(https://fonts.googleapis.com/css?family=Lato:400,700,900);

    .ReadMsgBody {
        width: 100%;
        background-color: #ffffff;
    }

    .ExternalClass {
        width: 100%;
        background-color: #ffffff;
    }

    .ExternalClass, .ExternalClass p, .ExternalClass span, .ExternalClass font, .ExternalClass td, .ExternalClass div {
        line-height: 100%;
    }

    html {
        width: 100%;
    }

    body {
        -webkit-text-size-adjust: none;
        -ms-text-size-adjust: none;
        margin: 0;
        padding: 0;
    }

    table {
        border-spacing: 0;
        border-collapse: collapse;
    }

    table td {
        border-collapse: collapse;
    }

    .yshortcuts a {
        border-bottom: none !important;
    }

    img {
        display: block !important;
    }

    a {
        text-decoration: none;
        color: #a0cf50;
    }

    /* Media Queries */

    @media only screen and (max-width: 600px) {
        body {
            width: auto !important;
        }

        table[class="table600"] {
            width: 100% !important;
        }

        table[class="table-container"] {
            width: 90% !important;
        }

        table[class="container2-2"] {
            width: 47% !important;
            text-align: left !important;
        }

        table[class="full-width"] {
            width: 100% !important;
            text-align: center !important;
        }

        img[class="img-full"] {
            width: 100% !important;
            height: auto !important;
        }
    }

    @media only screen and (max-width: 480px) {
        body {
            width: 100% !important;
        }

        table[class="table600"] {
            width: 100% !important;
        }

        table[class="table-container"] {
            width: 82% !important;
        }

        table[class="container2-2"] {
            width: 100% !important;
            text-align: left !important;
        }

        table[class="full-width"] {
            width: 100% !important;
            text-align: center !important;
        }

        img[class="img-full"] {
            width: 100% !important;
        }
    }

</style>
<div class="module-container" data-module="only_logo">    <!-- Only Logo -->
    <table width="100%" align="center" border="0" cellpadding="0" cellspacing="0">
        <tbody>
        <tr>
            <td data-bgcolor="Main" align="center">
                <table class="table600" width="600" border="0" cellpadding="0" cellspacing="0" style="margin: 15px;"
                       bgcolor="#ffffff">
                    <tbody>
                    <tr>
                        <td data-editable="image" align="center">
                            <a href="http://www.only.in/">
                                <img id="logoImage"
                                     src="https://www.vphrase.com/wp-content/uploads/2017/09/vPhrase_logo_large.png"
                                     alt="img" height="auto"
                                     style="margin-right:0px !important; margin-left:0px !important; padding-top:10px;">
                            </a>
                        </td>
                    </tr>
                    </tbody>
                </table>
            </td>
        </tr>
        </tbody>
    </table>
</div>
<div class="module-container" data-module="only_module_image">    <!-- ARTICLE FULL -->
    <table width="100%" align="center" border="0" cellpadding="0" cellspacing="0">
        <tbody>
        <tr>
            <td data-bgcolor="Main" align="center">
                <table class="table600" width="600" border="0" cellpadding="0" cellspacing="0" bgcolor="#ffffff">
                    <tbody>
                    <tr>
                        <td height="30" style="font-size: 1px; line-height: 30px;">&nbsp;</td>
                    </tr>
                    {% for img in img_src %}
                        <tr>

                            {% if len == 1 %}
                                <td data-editable="image" align="center">
                                    <img class="img-full"
                                         src="{{ img }}" alt="img"
                                         width="600" height="auto">
                                </td>
                            {% else %}
                                <td data-editable="image">
                                    <img class="img-not-full"
                                         src="{{ img }}" alt="img"
                                         width="300" height="auto" style="padding: 15px; margin: 15px; display: flex">
                                </td>
                            {% endif %}
                        </tr>
                    {% endfor %}
                    <tr>
                        <td height="30" style="font-size: 1px; line-height: 30px;">&nbsp;</td>
                    </tr>
                    </tbody>
                </table>
            </td>
        </tr>
        </tbody>
    </table>
    <!-- END ARTICLE FULL -->
</div>

basic/templates/basic/email_sending_complete.html
{% extends 'basic/base.html' %}
{% block content %}
    <div class="container">
        <div class="row" style="text-align: center">
            <div class="col-md-8 col-md-offset-2" align="center">
                <h2 align="center">
                    Please wait we are sending Mails to subscribed user.
                </h2>
            </div>
        </div>
    </div>
{% endblock %}

basic/templates/basic/index.html
{% extends 'basic/base.html' %}
{% load static %}
{% block style %}
    <link type="text/css" href="{% static 'css/index.css' %}">
{% endblock style %}
{% block content %}
    <style>
        #id_email_address {
            background-color: #fff;
            border-color: #dbdbdb;
            border-radius: 5px;
            color: #363636;
            box-shadow: inset 0 1px 2px rgba(10, 10, 10, .1);
            max-width: 100%;
            width: 50%;
            height: 35px;
        }
    </style>
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <form id="subscribe_user" method="Post" role="form" action="{% url 'basic:home' %}">
                    {% csrf_token %}
                    <div class="row">
                        <div class="col-md-12" align="center">
                            {{ add_form.email_address }}

                            {% if add_form.email_address.errors %}
                                <div class="alert alert-danger" style="width: 50%!important;">
                                    {{ add_form.email_address.errors }}
                                </div>

                            {% endif %}
                        </div>
                    </div>
                    <div class="row" style="margin-top:15px">
                        <div class="col-md-12" align="center">
                            <button type="submit" id="subscribe" class="btn btn-default"
                                    style="background-color: #00bda0; color: #fff">Subscribe
                            </button>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
    <hr>
    <div class="container">
        <div class="row">
            <div class="col-md-12" align="center">
                <a href="{% url 'basic:upload_templates' %}">
                    <button class="btn btn-default" style="background-color: #00bda0; color: #fff">Upload Templates
                    </button>
                </a>
            </div>
        </div>
    </div>
    <hr>
    <div class="container">
        <div class="row">
            {% for templates in email_templates %}
                <div class="col-md-4">
                    <div class="thumbnail">
                        {#To-Do: Change the hard coded address to real website address#}
                        <a href='http://127.0.0.1:8000/media/{{ templates }}'>
                            <h1 align="center">
                                {{ templates | truncatechars:15 }}
                            </h1>
                        </a>
                        <hr>
                        <div>
                            <a href="{% url 'basic:send_template' pk=templates.id %}">
                                <p align="center">
                                    <button  class="btn btn-default" style="background-color: #00bda0; color: #fff">
                                        Send
                                    </button>
                                </p>
                            </a>
                            {#                            <hr>#}
                            {#                            <a href="{% url 'basic:parse_template' pk=templates.id %}" >#}
                            {#                                <p align="center">#}
                            {#                                    <button  class="btn btn-default" style="background-color: #00bda0; color: #fff">#}
                            {#                                        Parse#}
                            {#                                    </button>#}
                            {#                                </p>#}
                            {#                            </a>#}
                        </div>
                    </div>
                </div>
            {% endfor %}
        </div>
    </div>
{% endblock %}

basic/templates/basic/upload_templates.html
{% extends 'basic/base.html' %}
{% block content %}
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <form method="Post" role="form" enctype="multipart/form-data">
                    <div class="col-md-8" align="center">
                        {% for form in upload_form %}
                            {{ form }}
                        {% endfor %}
                        {% for form in upload_form.errors %}
                            {{ form }}
                        {% endfor %}
                    </div>
                    <div class="col-md-4">
                        <button class="btn btn-default" style="background-color: #00bda0; color: #fff" type="submit">
                            Upload
                        </button>
                    </div>
                    {% csrf_token %}
                </form>
            </div>
        </div>
    </div>
{% endblock %}